name: calorie_tracker
description: "A modern calorie tracker application."
publish_to: "none"
version: 1.0.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.0 # or latest stable version
  google_mobile_ads: ^5.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  http: ^1.2.0
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "lib/assets/app_icon3.png"
  adaptive_icon_background: "#ffffff"
  min_sdk_android: 21 # Optional, ensures compatibility
